export const ALWAYS_ALLOWED_ROUTES = [
  'overview',
  'cloud_code',
  'jobs',
  'deployments',
  'webhooks',
  'config',
  'web-deployment',
  'Overview',
  'Web Deployment',
  'settings',
  'App Settings',
  'server-settings',
  'plan-usage',
  'Plan Usage',
  'Logs',
  'logs',
  'analytics',
  'reports',
  'Slow Requests',
  'App Security Report',
  'Advisors',
  'security',
  'domain-settings',
  'Domain Settings',
  'Advanced Options',
  'advanced-options',
  'environment-variable',
  'Environment Variable',
  'Environment Variables',
  'environment-variables',
  'social-auth',
  'Social Auth',
  'Notifications',
  'Notification',
  'notification',
  'notification/email',
  'notification/email/verification',
  'notification/email/password-reset',
  'push/android-settings',
  'push/ios-settings',
  'server-url-live-query',
  'Server URL & Live Query',
];

export const canAccess = (serverInfo, route) => {
  if (ALWAYS_ALLOWED_ROUTES.includes(route)) {
    return true;
  }
  return serverInfo.status === 'SUCCESS';
}
